server:
  port: 8761
logging:
  config: classpath:logback-spring.xml  #指定配置文件

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  profiles:
    active: dev
  freemarker:
    prefer-file-system-access: true
  application:
    name: eurka-server

mybatis:
  type-aliases-package: com.longi.dap.entity
  mapper-locations: classpath:mappers/*.xml
